// qwik/src/components/post-navigation.tsx
import type { JSXOutput } from '@qwik.dev/core'
import type { PostReference } from '../lib/content-shared'
import type { SupportedLocale } from '../lib/locales'
import { component$ } from '@qwik.dev/core'
import { Link } from '@qwik.dev/router'
import { formatDate, isDraftPost, isRecentPost } from '../lib/content-shared'

interface PostNavigationProps {
  locale: SupportedLocale
  newer: PostReference | null
  older: PostReference | null
}

function PostNavLink(props: {
  locale: SupportedLocale
  post: PostReference
  direction: 'newer' | 'older'
}): JSXOutput {
  const isExternal = props.post.url.includes('://')
  const arrowClass = props.direction === 'newer'
    ? 'i-ri-arrow-left-s-line'
    : 'i-ri-arrow-right-s-line'
  const content = (
    <>
      {props.direction === 'newer'
        ? <div aria-hidden="true" class={`${arrowClass} flex-none text-lg op40`} />
        : null}
      <div class={props.direction === 'older' ? 'min-w-0 flex flex-col items-end' : 'min-w-0 flex flex-col'}>
        <span class={props.direction === 'older' ? 'truncate text-right text-base leading-snug' : 'truncate text-base leading-snug'}>
          {props.post.title}
        </span>
        <span class="mt-0.5 text-base op45">
          {isDraftPost(props.post.type) ? '🚧 ' : ''}
          {isRecentPost(props.post.date, props.post.updated) && !isDraftPost(props.post.type) ? '🌱 ' : ''}
          {formatDate(props.locale, props.post.date)}
        </span>
      </div>
      {props.direction === 'older'
        ? <div aria-hidden="true" class={`${arrowClass} flex-none text-lg op40`} />
        : null}
    </>
  )

  const classes = [
    'flex-1 rounded-lg border border-base px-4 py-3 no-underline op65 transition-all hover:bg-black/4 hover:op100 dark:hover:bg-white/8',
    props.direction === 'older' ? 'flex items-center justify-end gap-3' : 'flex items-center gap-3',
  ].join(' ')

  return isExternal
    ? (
        <a href={props.post.url} target="_blank" rel="noopener noreferrer" class={classes}>
          {content}
        </a>
      )
    : (
        <Link href={props.post.url} class={classes}>
          {content}
        </Link>
      )
}

export const PostNavigation = component$<PostNavigationProps>(
  ({ locale, newer, older }) => {
    if (!newer && !older)
      return null

    return (
      <nav class="mb-6 mt-9 flex flex-col items-stretch gap-3 sm:flex-row sm:gap-4">
        {newer
          ? <PostNavLink locale={locale} post={newer} direction="newer" />
          : <div class="flex-1" />}
        {older
          ? <PostNavLink locale={locale} post={older} direction="older" />
          : <div class="flex-1" />}
      </nav>
    )
  },
)

// src/components/PostNavigation.vue
<script setup lang="ts">
import type { RouteRecordNormalized } from 'vue-router'
import type { Post } from '~/types'
import { formatDate, isDraftPost, isPostVisible, isRecentPost } from '~/logics'
import { getLocaleFromPath } from '~/logics/i18n-path'

const props = defineProps<{
  currentPath: string
  type?: string
}>()

const router = useRouter()
const route = useRoute()

const currentLocale = computed(() => {
  return getLocaleFromPath(route.path)
})

const postType = computed(() => props.type || 'blog')

const siblings = computed<Post[]>(() => {
  return router.getRoutes()
    .filter((r: RouteRecordNormalized) =>
      r.path.startsWith(`/${currentLocale.value}/articles`)
      && isPostVisible(r.meta.frontmatter || {}),
    )
    .filter((r: RouteRecordNormalized) =>
      !r.path.endsWith('.html')
      && (r.meta.frontmatter?.type || 'blog').split('+').includes(postType.value),
    )
    .map((r: RouteRecordNormalized) => ({
      path: r.path,
      title: r.meta.frontmatter?.title,
      date: r.meta.frontmatter?.date,
      updated: r.meta.frontmatter?.updated,
      lang: r.meta.frontmatter?.lang,
      duration: r.meta.frontmatter?.duration,
      type: r.meta.frontmatter?.type,
    }))
    .sort((a, b) => +new Date(b.date) - +new Date(a.date))
})

const currentIndex = computed(() => {
  return siblings.value.findIndex(p => p.path === props.currentPath)
})

const newerPost = computed(() => {
  if (currentIndex.value <= 0)
    return null
  return siblings.value[currentIndex.value - 1]
})
const olderPost = computed(() => {
  if (currentIndex.value < 0 || currentIndex.value >= siblings.value.length - 1)
    return null
  return siblings.value[currentIndex.value + 1]
})

const hasNavigation = computed(() => newerPost.value || olderPost.value)
</script>

<template>
  <nav
    v-if="hasNavigation"
    class="post-nav"
    flex="~ col sm:row gap-3 sm:gap-4"
    items-stretch
  >
    <RouterLink
      v-if="newerPost"
      :to="newerPost.path"
      class="post-nav-link post-nav-newer flex-1"
      flex="~ gap-3 items-center"
    >
      <div
        i-ri:arrow-left-s-line
        flex-none text-lg op40
      />
      <div flex="~ col" min-w-0>
        <span class="post-nav-title" text-base leading-snug>
          {{ newerPost.title }}
        </span>
        <span class="post-nav-date" text-base op45 mt-0.5>
          <span v-if="isDraftPost(newerPost.type)">🚧 </span>
          <span v-if="isRecentPost(newerPost.date, newerPost.updated) && !isDraftPost(newerPost.type)">🌱 </span>{{ formatDate(newerPost.date, false, currentLocale) }}
        </span>
      </div>
    </RouterLink>

    <div v-if="!newerPost" flex-1 />

    <RouterLink
      v-if="olderPost"
      :to="olderPost.path"
      class="post-nav-link post-nav-older flex-1"
      flex="~ gap-3 items-center justify-end"
    >
      <div flex="~ col items-end" min-w-0>
        <span class="post-nav-title" text-base leading-snug text-right>
          {{ olderPost.title }}
        </span>
        <span class="post-nav-date" text-base op45 mt-0.5>
          <span v-if="isDraftPost(olderPost.type)">🚧 </span>
          <span v-if="isRecentPost(olderPost.date, olderPost.updated) && !isDraftPost(olderPost.type)">🌱 </span>{{ formatDate(olderPost.date, false, currentLocale) }}
        </span>
      </div>
      <div
        i-ri:arrow-right-s-line
        flex-none text-lg op40
      />
    </RouterLink>

    <div v-if="!olderPost" flex-1 />
  </nav>
</template>

<style scoped>
.post-nav-link {
  padding: 0.75rem 1rem;
  border: 1px solid rgba(125, 125, 125, 0.25);
  border-radius: 0.5rem;
  text-decoration: none !important;
  transition: all 0.25s ease;
  opacity: 0.65;
}

.post-nav-link:hover {
  opacity: 1;
  border-color: rgba(125, 125, 125, 0.35);
  background: rgba(125, 125, 125, 0.06);
}

.post-nav-title {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.dark .post-nav-link {
  border-color: rgba(125, 125, 125, 0.4);
}

.dark .post-nav-link:hover {
  border-color: rgba(125, 125, 125, 0.5);
  background: rgba(125, 125, 125, 0.08);
}
</style>
